### ISSUE TITLE
500 on every request

### ISSUE THREAD

**Issue by callumacrae** [eddyerburgh/vue-cli-ssr-example#26]
Hey Edd!

I can't get this running at all. I'm following the instructions in the readme:

```
yarn
yarn build
yarn start
```

Then it starts the server, but when I make a request:

```
[vue-router] Failed to resolve async component default: ReferenceError: document is not defined
[vue-router] uncaught error during route navigation:
ReferenceError: document is not defined
    at js/main.55944624.js:1:467
    at new Promise (<anonymous>)
    at Function.o.e (js/main.55944624.js:1:359)
    at v (js/main.55944624.js:1:3628)
    at /Users/callumacrae/Sites/tmp/vue-cli-ssr-example/node_modules/vue-router/dist/vue-router.common.js:1768:17
    at /Users/callumacrae/Sites/tmp/vue-cli-ssr-example/node_modules/vue-router/dist/vue-router.common.js:1795:66
    at Array.map (<anonymous>)
    at /Users/callumacrae/Sites/tmp/vue-cli-ssr-example/node_modules/vue-router/dist/vue-router.common.js:1795:38
    at Array.map (<anonymous>)
    at flatMapComponents (/Users/callumacrae/Sites/tmp/vue-cli-ssr-example/node_modules/vue-router/dist/vue-router.common.js:1794:26)
error during render : /
ReferenceError: document is not defined
    at js/main.55944624.js:1:467
    at new Promise (<anonymous>)
    at Function.o.e (webpack/bootstrap:50:57)
    at v (src/router.js:10:2)
    at /Users/callumacrae/Sites/tmp/vue-cli-ssr-example/node_modules/vue-router/dist/vue-router.common.js:1768:17
    at /Users/callumacrae/Sites/tmp/vue-cli-ssr-example/node_modules/vue-router/dist/vue-router.common.js:1795:66
    at Array.map (<anonymous>)
    at /Users/callumacrae/Sites/tmp/vue-cli-ssr-example/node_modules/vue-router/dist/vue-router.common.js:1795:38
    at Array.map (<anonymous>)
    at flatMapComponents (/Users/callumacrae/Sites/tmp/vue-cli-ssr-example/node_modules/vue-router/dist/vue-router.common.js:1794:26)
```

My node version is 10.13.0 - any ideas what could be causing this? I'm guessing I'll need to provide more info but have no idea what…

**Comment by ulich** [comment]
You can have a look at my PR to fix exactly this issue: https://github.com/eddyerburgh/vue-cli-ssr-example/pull/25

**Comment by callumacrae** [comment]
That doesn't seem to fix this issue.

**Comment by renanbronchart** [comment]
Same problem for me. It impossible to start project with build

**Comment by ulich** [comment]
@renanbronchart does #25 fix the issue for you?

**Comment by renanbronchart** [comment]
No that doesn't fix this issue.

Problem reproduction:
```
yarn serve
```
- ```localhost:8081``` works well

```
yarn build
yarn start
```
- ```localhost:8080``` doesn't work (error 500 described above)
- ```localhost:8081``` doesn't work

I tested an other way:
```
yarn build
yarn serve
// cut server with ctrl+c
yarn start
```
- ```localhost:8080``` seems work but :
     - reload page when use router link, 
     - Maybe it is cause by this error ```[HPM] Error occurred while trying to proxy request /main.js```

**Comment by renanbronchart** [comment]
> @renanbronchart does #25 fix the issue for you?

Sorry, yes it works with add on vue.config.js :
```
css: {
   extract: process.env.NODE_ENV === 'production' && !TARGET_NODE
 },
```
