### ISSUE TITLE
Async Components doesn't load

### ISSUE THREAD

**Issue by sns45** [eddyerburgh/vue-cli-ssr-example#7]
If in my App.vue, I have multiple components that I want to load Asynchronously. 
For example:
`HelloWorld : () => import('./components/HelloWorld.vue'),
  HelloWorld2 : () => import('./components/HelloWorld2.vue')`

`npm run build` is successful but when I do `npm run start` and visit `http://localhost:8080/` then I get a 500 internal error:

`ReferenceError: document is not defined
    at r.(anonymous function).r.(anonymous function).u.(anonymous function).a.push.r.(anonymous function).Promise.then.r.(anonymous function) (webpack/bootstrap:54:0)
    at new Promise (<anonymous>)
    at Function.module.exports.o.e (webpack/bootstrap:50:57)
    at HelloWorld2 (src/App.vue?1160:1:318)
    at resolveAsyncComponent (/Users/shsharma/vue-cli-ssr-example/node_modules/vue/dist/vue.runtime.common.js:2336:15)
    at createComponent (/Users/shsharma/vue-cli-ssr-example/node_modules/vue/dist/vue.runtime.common.js:4217:12)
    at _createElement (/Users/shsharma/vue-cli-ssr-example/node_modules/vue/dist/vue.runtime.common.js:4418:15)
    at createElement (/Users/shsharma/vue-cli-ssr-example/node_modules/vue/dist/vue.runtime.common.js:4355:10)
    at vm._c (/Users/shsharma/vue-cli-ssr-example/node_modules/vue/dist/vue.runtime.common.js:4487:42)
    at Proxy.a (src/App.vue:12:0)
`

Here's how to reproduce:

Clone https://github.com/sns45/vue-cli-ssr-example

Run `npm install` , `npm run build` , `npm run start`

It works in development mode but not production mode.

**Comment by Drezdenozk** [comment]
Hello comrad, seems like webpack config contain some error, try next:
vue.config.js

- remove line "    node: TARGET_NODE ? undefined : false,"
and ..
- optimizeSSR: false change to optimizeSSR: true

It's work for me
