### ISSUE TITLE
Integration of SSR with Vuetify?

### ISSUE THREAD

**Issue by Renaud009** [eddyerburgh/vue-cli-ssr-example#8]
Doesn't integrate well with vuetify. Any help or hint would be appreciated.

I'm getting this error at the moment when trying to render home page after npm run ssr:serve:
    at Promise.all.then.arr (.../vuejs-test2/node_modules/clipboardy/node_modules/execa/index.js:236:11)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:11934) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without
a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:11934) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error during render : /
/.../node_modules/vuetify/lib/index.js:1
(function (exports, require, module, __filename, __dirname) { import Vuetify from './components/Vuetify';
                                                                     ^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)
    at Object.runInThisContext (vm.js:319:10)
    at Module._compile (internal/modules/cjs/loader.js:685:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at r (/.../vuejs-test2/node_modules/vue-server-renderer/build.js:8346:16)
    at Object.vuetify/lib (webpack:/external "vuetify/lib":1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module../src/App.vue (src/App.vue:1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module../src/entry-server.js (main.js:1782:66)

**Comment by Jambazishvili** [comment]
Hi, I have very similar problem, please give advice / help. @Renaud009 have you found the solution?

**Comment by eddyerburgh** [comment]
In vue.config.js update the externals whitelist:

```js
// vue.config.js

module.exports = {
  // ..
  externals: TARGET_NODE ? nodeExternals({
    whitelist: [/\.css$/, /vuetify/]
  }) : undefined,
}
```

This tells Webpack to bundle the vuetify code in `Vuetify/lib` (which uses ES modules).
